-- Script de création manuelle des tables Oracle
-- Remplacer {PREFIX} par votre préfixe de système (3 à 10 lettres)

-- Séquences pour la génération des identifiants
CREATE SEQUENCE {PREFIX}_SEQ_PROCESSUS START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE {PREFIX}_SEQ_HISTORIQUE START WITH 1 INCREMENT BY 1 NOCACHE;

-- Table pour stocker les contextes de processus
CREATE TABLE {PREFIX}_PROCESS_CONTEXT (
    ID_PROCESSUS NUMBER(10) PRIMARY KEY,
    ID_PROCESSUS_PARENT NUMBER(10),
    ID_NOEUD_PARENT VARCHAR2(255),
    ID_AGREGAT VARCHAR2(255),
    DONNEES CLOB,
    ETAT_INTERNE CLOB,
    DATE_DEBUT TIMESTAMP NOT NULL,
    DATE_DERNIERE_EXECUTION TIMESTAMP,
    DATE_COMPLETION TIMESTAMP,
    ID_NOEUD_COURANT VARCHAR2(255),
    NOM_DEFINITION VARCHAR2(255),
    VERSION_DEFINITION VARCHAR2(50),
    STATUT NUMBER(10) NOT NULL,
    CONSTRAINT CHK_{PREFIX}_STATUT CHECK (STATUT BETWEEN 0 AND 5)
);

-- Table pour l'historique d'exécution des nœuds
CREATE TABLE {PREFIX}_HISTORIQUE_EXECUTION_NOEUD (
    ID_HISTORIQUE NUMBER(10) PRIMARY KEY,
    ID_PROCESSUS NUMBER(10) NOT NULL,
    ID_NOEUD VARCHAR2(255) NOT NULL,
    NOM_NOEUD VARCHAR2(500),
    TYPE_NOEUD NUMBER(10) NOT NULL,
    DATE_DEBUT TIMESTAMP NOT NULL,
    DATE_FIN TIMESTAMP NOT NULL,
    DUREE_MS NUMBER(19) NOT NULL,
    SUCCES NUMBER(1) NOT NULL,
    MESSAGE_ERREUR VARCHAR2(4000),
    ID_NOEUD_SUIVANT VARCHAR2(255),
    CONSTRAINT FK_{PREFIX}_HIST_PROC 
        FOREIGN KEY (ID_PROCESSUS) 
        REFERENCES {PREFIX}_PROCESS_CONTEXT(ID_PROCESSUS) 
        ON DELETE CASCADE
);

-- Index pour améliorer les performances
CREATE INDEX IX_{PREFIX}_01_PROCESS_CONTEXT ON {PREFIX}_PROCESS_CONTEXT(ID_AGREGAT);
CREATE INDEX IX_{PREFIX}_02_PROCESS_CONTEXT ON {PREFIX}_PROCESS_CONTEXT(STATUT);
CREATE INDEX IX_{PREFIX}_03_PROCESS_CONTEXT ON {PREFIX}_PROCESS_CONTEXT(DATE_DEBUT);
CREATE INDEX IX_{PREFIX}_01_HISTORIQUE_EXECUTION_NOEUD ON {PREFIX}_HISTORIQUE_EXECUTION_NOEUD(ID_PROCESSUS);
CREATE INDEX IX_{PREFIX}_02_HISTORIQUE_EXECUTION_NOEUD ON {PREFIX}_HISTORIQUE_EXECUTION_NOEUD(ID_NOEUD);
CREATE INDEX IX_{PREFIX}_03_HISTORIQUE_EXECUTION_NOEUD ON {PREFIX}_HISTORIQUE_EXECUTION_NOEUD(DATE_DEBUT);

-- Commentaires sur PROCESS_CONTEXT
COMMENT ON SEQUENCE {PREFIX}_SEQ_PROCESSUS IS 'Séquence pour la génération des identifiants de processus';
COMMENT ON SEQUENCE {PREFIX}_SEQ_HISTORIQUE IS 'Séquence pour la génération des identifiants d''historique';

COMMENT ON TABLE {PREFIX}_PROCESS_CONTEXT IS 'Table stockant les contextes d''exécution des processus BPM';
COMMENT ON COLUMN {PREFIX}_PROCESS_CONTEXT.ID_PROCESSUS IS 'Identifiant unique du processus';
COMMENT ON COLUMN {PREFIX}_PROCESS_CONTEXT.ID_PROCESSUS_PARENT IS 'Identifiant du processus parent (NULL si processus racine)';
COMMENT ON COLUMN {PREFIX}_PROCESS_CONTEXT.ID_AGREGAT IS 'Identifiant de l''agrégat métier associé';
COMMENT ON COLUMN {PREFIX}_PROCESS_CONTEXT.DONNEES IS 'Variables du processus en format JSON';
COMMENT ON COLUMN {PREFIX}_PROCESS_CONTEXT.ETAT_INTERNE IS 'État interne du moteur (ex: date d''attente WaitUntilDate) en format JSON';
COMMENT ON COLUMN {PREFIX}_PROCESS_CONTEXT.DATE_DEBUT IS 'Date/heure de démarrage du processus';
COMMENT ON COLUMN {PREFIX}_PROCESS_CONTEXT.DATE_DERNIERE_EXECUTION IS 'Dernière date/heure d''exécution';
COMMENT ON COLUMN {PREFIX}_PROCESS_CONTEXT.DATE_COMPLETION IS 'Date/heure de complétion du processus';
COMMENT ON COLUMN {PREFIX}_PROCESS_CONTEXT.ID_NOEUD_COURANT IS 'Identifiant du nœud courant';
COMMENT ON COLUMN {PREFIX}_PROCESS_CONTEXT.NOM_DEFINITION IS 'Nom de la définition du processus';
COMMENT ON COLUMN {PREFIX}_PROCESS_CONTEXT.VERSION_DEFINITION IS 'Version de la définition du processus';
COMMENT ON COLUMN {PREFIX}_PROCESS_CONTEXT.ID_NOEUD_PARENT IS 'Identifiant du noeud parent ayant lancé ce sous-processus (NULL si processus racine)';
COMMENT ON COLUMN {PREFIX}_PROCESS_CONTEXT.STATUT IS 'Statut du processus (0=EnCours, 1=AttentInteraction, 2=AttentDate, 3=AttentSignal, 4=Complete, 5=Echoue)';

-- Commentaires sur HISTORIQUE_EXECUTION_NOEUD
COMMENT ON TABLE {PREFIX}_HISTORIQUE_EXECUTION_NOEUD IS 'Historique d''exécution des nœuds du processus';
COMMENT ON COLUMN {PREFIX}_HISTORIQUE_EXECUTION_NOEUD.ID_HISTORIQUE IS 'Identifiant unique de l''entrée d''historique';
COMMENT ON COLUMN {PREFIX}_HISTORIQUE_EXECUTION_NOEUD.ID_PROCESSUS IS 'Identifiant du processus';
COMMENT ON COLUMN {PREFIX}_HISTORIQUE_EXECUTION_NOEUD.ID_NOEUD IS 'Identifiant du nœud exécuté';
COMMENT ON COLUMN {PREFIX}_HISTORIQUE_EXECUTION_NOEUD.NOM_NOEUD IS 'Nom du nœud';
COMMENT ON COLUMN {PREFIX}_HISTORIQUE_EXECUTION_NOEUD.TYPE_NOEUD IS 'Type de nœud (0=Metier, 1=Decision, 2=Interactif, 3=AttentDate, 4=AttentSignal, 5=SousProcessus)';
COMMENT ON COLUMN {PREFIX}_HISTORIQUE_EXECUTION_NOEUD.DATE_DEBUT IS 'Date/heure de début d''exécution';
COMMENT ON COLUMN {PREFIX}_HISTORIQUE_EXECUTION_NOEUD.DATE_FIN IS 'Date/heure de fin d''exécution';
COMMENT ON COLUMN {PREFIX}_HISTORIQUE_EXECUTION_NOEUD.DUREE_MS IS 'Durée d''exécution en millisecondes';
COMMENT ON COLUMN {PREFIX}_HISTORIQUE_EXECUTION_NOEUD.SUCCES IS 'Indicateur de succès (1=succès, 0=échec)';
COMMENT ON COLUMN {PREFIX}_HISTORIQUE_EXECUTION_NOEUD.MESSAGE_ERREUR IS 'Message d''erreur si échec';
COMMENT ON COLUMN {PREFIX}_HISTORIQUE_EXECUTION_NOEUD.ID_NOEUD_SUIVANT IS 'Identifiant du prochain nœud';

-- Exemple de requêtes utiles:

-- Voir l'historique d'exécution d'un processus avec durée
-- SELECT NOM_NOEUD, TYPE_NOEUD, DATE_DEBUT, DATE_FIN, DUREE_MS, SUCCES
-- FROM {PREFIX}_HISTORIQUE_EXECUTION_NOEUD
-- WHERE ID_PROCESSUS = 123
-- ORDER BY DATE_DEBUT;

-- Voir la durée totale d'un processus
-- SELECT
--     ID_PROCESSUS,
--     DATE_DEBUT,
--     DATE_COMPLETION,
--     ROUND((EXTRACT(DAY FROM (DATE_COMPLETION - DATE_DEBUT)) * 24 * 60 * 60 +
--            EXTRACT(HOUR FROM (DATE_COMPLETION - DATE_DEBUT)) * 60 * 60 +
--            EXTRACT(MINUTE FROM (DATE_COMPLETION - DATE_DEBUT)) * 60 +
--            EXTRACT(SECOND FROM (DATE_COMPLETION - DATE_DEBUT))) * 1000) AS DUREE_MS
-- FROM {PREFIX}_PROCESS_CONTEXT
-- WHERE ID_PROCESSUS = 123;

-- Statistiques par type de nœud
-- SELECT 
--     TYPE_NOEUD,
--     COUNT(*) AS TOTAL_EXECUTIONS,
--     AVG(DUREE_MS) AS DUREE_MOYENNE_MS,
--     MAX(DUREE_MS) AS DUREE_MAX_MS,
--     SUM(CASE WHEN SUCCES = 1 THEN 1 ELSE 0 END) AS NOMBRE_SUCCES,
--     SUM(CASE WHEN SUCCES = 0 THEN 1 ELSE 0 END) AS NOMBRE_ECHECS
-- FROM {PREFIX}_HISTORIQUE_EXECUTION_NOEUD
-- GROUP BY TYPE_NOEUD;

-- Processus en cours d'exécution
-- SELECT ID_PROCESSUS, ID_AGREGAT, DATE_DEBUT, STATUT, ID_NOEUD_COURANT
-- FROM {PREFIX}_PROCESS_CONTEXT
-- WHERE STATUT IN (0, 1, 2, 3); -- EnCours, AttentInteraction, AttentDate, AttentSignal

-- Processus qui ont échoué
-- SELECT ID_PROCESSUS, ID_AGREGAT, DATE_DEBUT, DATE_DERNIERE_EXECUTION
-- FROM {PREFIX}_PROCESS_CONTEXT
-- WHERE STATUT = 5; -- Echoue

-- Exemple d'utilisation avec le préfixe "ABC":
-- CREATE TABLE ABC_PROCESS_CONTEXT (...)
-- CREATE TABLE ABC_HISTORIQUE_EXECUTION_NOEUD (...)
-- CREATE INDEX IX_ABC_01_PROCESS_CONTEXT ON ABC_PROCESS_CONTEXT(ID_AGREGAT);
-- CREATE INDEX IX_ABC_02_PROCESS_CONTEXT ON ABC_PROCESS_CONTEXT(STATUT);
-- CREATE INDEX IX_ABC_03_PROCESS_CONTEXT ON ABC_PROCESS_CONTEXT(DATE_DEBUT);
-- CREATE INDEX IX_ABC_01_HISTORIQUE_EXECUTION_NOEUD ON ABC_HISTORIQUE_EXECUTION_NOEUD(ID_PROCESSUS);
-- CREATE INDEX IX_ABC_02_HISTORIQUE_EXECUTION_NOEUD ON ABC_HISTORIQUE_EXECUTION_NOEUD(ID_NOEUD);
-- CREATE INDEX IX_ABC_03_HISTORIQUE_EXECUTION_NOEUD ON ABC_HISTORIQUE_EXECUTION_NOEUD(DATE_DEBUT);
