-- Script de création manuelle des tables Oracle
-- Remplacer {PREFIX} par votre préfixe de système (3 à 10 lettres)

-- Séquences pour la génération des identifiants
CREATE SEQUENCE {PREFIX}_SEQ_PROCESSUS START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE {PREFIX}_SEQ_HISTORIQUE START WITH 1 INCREMENT BY 1 NOCACHE;

-- Table pour stocker les contextes de processus
CREATE TABLE {PREFIX}_PROCESS_CONTEXT (
    NO_SEQ_PROCS NUMBER(10) PRIMARY KEY,
    NO_SEQ_PROCS_PARN NUMBER(10),
    ID_NOEUD_PARN VARCHAR2(255),
    ID_ENTI_AFFA NUMBER(10),
    VAR_PROCS CLOB,
    DH_ATTEN DATE,
    SIGNL_ATTENTION VARCHAR2(255),
    DH_DEB DATE NOT NULL,
    DH_EXEC DATE,
    DH_COMPL DATE,
    ID_NOEUD_COUR VARCHAR2(255),
    ID_DEFIN VARCHAR2(255),
    VERSI_DEFIN VARCHAR2(50),
    STAT_PROCS NUMBER(10) NOT NULL,
    CONSTRAINT CHK_{PREFIX}_STAT_PROCS CHECK (STAT_PROCS BETWEEN 0 AND 5)
);

-- Table pour l'historique d'exécution des nœuds
CREATE TABLE {PREFIX}_HISTORIQUE_EXECUTION_NOEUD (
    NO_SEQ_NOEUD NUMBER(10) PRIMARY KEY,
    NO_SEQ_PROCS NUMBER(10) NOT NULL,
    ID_NOEUD VARCHAR2(255) NOT NULL,
    NOM_NOEUD VARCHAR2(255),
    TYPE_NOEUD NUMBER(10) NOT NULL,
    DH_DEB DATE NOT NULL,
    DH_FIN DATE NOT NULL,
    IND_SUCCS NUMBER(1) NOT NULL,
    MESS_ERR VARCHAR2(4000),
    ID_NOEUD_SUIV VARCHAR2(255),
    CONSTRAINT FK_{PREFIX}_HIST_PROC
        FOREIGN KEY (NO_SEQ_PROCS)
        REFERENCES {PREFIX}_PROCESS_CONTEXT(NO_SEQ_PROCS)
        ON DELETE CASCADE
);

-- Index pour améliorer les performances
CREATE INDEX IX_{PREFIX}_01_PROCESS_CONTEXT ON {PREFIX}_PROCESS_CONTEXT(ID_ENTI_AFFA);
CREATE INDEX IX_{PREFIX}_02_PROCESS_CONTEXT ON {PREFIX}_PROCESS_CONTEXT(STAT_PROCS);
CREATE INDEX IX_{PREFIX}_03_PROCESS_CONTEXT ON {PREFIX}_PROCESS_CONTEXT(DH_DEB);
CREATE INDEX IX_{PREFIX}_01_HISTORIQUE_EXECUTION_NOEUD ON {PREFIX}_HISTORIQUE_EXECUTION_NOEUD(NO_SEQ_PROCS);
CREATE INDEX IX_{PREFIX}_02_HISTORIQUE_EXECUTION_NOEUD ON {PREFIX}_HISTORIQUE_EXECUTION_NOEUD(ID_NOEUD);
CREATE INDEX IX_{PREFIX}_03_HISTORIQUE_EXECUTION_NOEUD ON {PREFIX}_HISTORIQUE_EXECUTION_NOEUD(DH_DEB);

-- Commentaires sur PROCESS_CONTEXT
COMMENT ON SEQUENCE {PREFIX}_SEQ_PROCESSUS IS 'Séquence pour la génération des identifiants de processus';
COMMENT ON SEQUENCE {PREFIX}_SEQ_HISTORIQUE IS 'Séquence pour la génération des identifiants d''historique';

COMMENT ON TABLE {PREFIX}_PROCESS_CONTEXT IS 'Table stockant les contextes d''exécution des processus BPM';
COMMENT ON COLUMN {PREFIX}_PROCESS_CONTEXT.NO_SEQ_PROCS IS 'Identifiant unique du processus';
COMMENT ON COLUMN {PREFIX}_PROCESS_CONTEXT.NO_SEQ_PROCS_PARN IS 'Identifiant du processus parent (NULL si processus racine)';
COMMENT ON COLUMN {PREFIX}_PROCESS_CONTEXT.ID_NOEUD_PARN IS 'Identifiant du noeud parent ayant lancé ce sous-processus (NULL si processus racine)';
COMMENT ON COLUMN {PREFIX}_PROCESS_CONTEXT.ID_ENTI_AFFA IS 'Identifiant de l''entité métier associée';
COMMENT ON COLUMN {PREFIX}_PROCESS_CONTEXT.VAR_PROCS IS 'Variables du processus en format JSON';
COMMENT ON COLUMN {PREFIX}_PROCESS_CONTEXT.DH_ATTEN IS 'Date cible du nœud WaitUntilDate (NULL si le processus n''attend pas une date)';
COMMENT ON COLUMN {PREFIX}_PROCESS_CONTEXT.SIGNL_ATTENTION IS 'Nom du signal attendu par le nœud WaitForSignal (NULL si le processus n''attend pas un signal)';
COMMENT ON COLUMN {PREFIX}_PROCESS_CONTEXT.DH_DEB IS 'Date/heure de démarrage du processus';
COMMENT ON COLUMN {PREFIX}_PROCESS_CONTEXT.DH_EXEC IS 'Dernière date/heure d''exécution';
COMMENT ON COLUMN {PREFIX}_PROCESS_CONTEXT.DH_COMPL IS 'Date/heure de complétion du processus';
COMMENT ON COLUMN {PREFIX}_PROCESS_CONTEXT.ID_NOEUD_COUR IS 'Identifiant du nœud courant';
COMMENT ON COLUMN {PREFIX}_PROCESS_CONTEXT.ID_DEFIN IS 'Nom de la définition du processus';
COMMENT ON COLUMN {PREFIX}_PROCESS_CONTEXT.VERSI_DEFIN IS 'Version de la définition du processus';
COMMENT ON COLUMN {PREFIX}_PROCESS_CONTEXT.STAT_PROCS IS 'Statut du processus (0=EnCours, 1=AttentInteraction, 2=AttentDate, 3=AttentSignal, 4=Complete, 5=Echoue)';

-- Commentaires sur HISTORIQUE_EXECUTION_NOEUD
COMMENT ON TABLE {PREFIX}_HISTORIQUE_EXECUTION_NOEUD IS 'Historique d''exécution des nœuds du processus';
COMMENT ON COLUMN {PREFIX}_HISTORIQUE_EXECUTION_NOEUD.NO_SEQ_NOEUD IS 'Identifiant unique de l''entrée d''historique';
COMMENT ON COLUMN {PREFIX}_HISTORIQUE_EXECUTION_NOEUD.NO_SEQ_PROCS IS 'Identifiant du processus';
COMMENT ON COLUMN {PREFIX}_HISTORIQUE_EXECUTION_NOEUD.ID_NOEUD IS 'Identifiant du nœud exécuté';
COMMENT ON COLUMN {PREFIX}_HISTORIQUE_EXECUTION_NOEUD.NOM_NOEUD IS 'Nom d''affichage du nœud exécuté';
COMMENT ON COLUMN {PREFIX}_HISTORIQUE_EXECUTION_NOEUD.TYPE_NOEUD IS 'Type de nœud (0=Metier, 1=Decision, 2=Interactif, 3=AttentDate, 4=AttentSignal, 5=SousProcessus)';
COMMENT ON COLUMN {PREFIX}_HISTORIQUE_EXECUTION_NOEUD.DH_DEB IS 'Date/heure de début d''exécution';
COMMENT ON COLUMN {PREFIX}_HISTORIQUE_EXECUTION_NOEUD.DH_FIN IS 'Date/heure de fin d''exécution';
COMMENT ON COLUMN {PREFIX}_HISTORIQUE_EXECUTION_NOEUD.IND_SUCCS IS 'Indicateur de succès (1=succès, 0=échec)';
COMMENT ON COLUMN {PREFIX}_HISTORIQUE_EXECUTION_NOEUD.MESS_ERR IS 'Message d''erreur si échec';
COMMENT ON COLUMN {PREFIX}_HISTORIQUE_EXECUTION_NOEUD.ID_NOEUD_SUIV IS 'Identifiant du prochain nœud';

-- Exemple de requêtes utiles:

-- Voir l'historique d'exécution d'un processus avec durée
-- SELECT ID_NOEUD, TYPE_NOEUD, DH_DEB, DH_FIN, IND_SUCCS
-- FROM {PREFIX}_HISTORIQUE_EXECUTION_NOEUD
-- WHERE NO_SEQ_PROCS = 123
-- ORDER BY DH_DEB;

-- Voir la durée totale d'un processus
-- SELECT
--     NO_SEQ_PROCS,
--     DH_DEB,
--     DH_COMPL,
--     ROUND((EXTRACT(DAY FROM (DH_COMPL - DH_DEB)) * 24 * 60 * 60 +
--            EXTRACT(HOUR FROM (DH_COMPL - DH_DEB)) * 60 * 60 +
--            EXTRACT(MINUTE FROM (DH_COMPL - DH_DEB)) * 60 +
--            EXTRACT(SECOND FROM (DH_COMPL - DH_DEB))) * 1000) AS DUREE_MS
-- FROM {PREFIX}_PROCESS_CONTEXT
-- WHERE NO_SEQ_PROCS = 123;

-- Statistiques par type de nœud
-- SELECT
--     TYPE_NOEUD,
--     COUNT(*) AS TOTAL_EXECUTIONS,
--     AVG(EXTRACT(SECOND FROM (DH_FIN - DH_DEB)) * 1000) AS DUREE_MOYENNE_MS,
--     MAX(EXTRACT(SECOND FROM (DH_FIN - DH_DEB)) * 1000) AS DUREE_MAX_MS,
--     SUM(CASE WHEN IND_SUCCS = 1 THEN 1 ELSE 0 END) AS NOMBRE_SUCCES,
--     SUM(CASE WHEN IND_SUCCS = 0 THEN 1 ELSE 0 END) AS NOMBRE_ECHECS
-- FROM {PREFIX}_HISTORIQUE_EXECUTION_NOEUD
-- GROUP BY TYPE_NOEUD;

-- Processus en cours d'exécution
-- SELECT NO_SEQ_PROCS, ID_ENTI_AFFA, DH_DEB, STAT_PROCS, ID_NOEUD_COUR
-- FROM {PREFIX}_PROCESS_CONTEXT
-- WHERE STAT_PROCS IN (0, 1, 2, 3); -- EnCours, AttentInteraction, AttentDate, AttentSignal

-- Processus qui ont échoué
-- SELECT NO_SEQ_PROCS, ID_ENTI_AFFA, DH_DEB, DH_EXEC
-- FROM {PREFIX}_PROCESS_CONTEXT
-- WHERE STAT_PROCS = 5; -- Echoue

-- Exemple d'utilisation avec le préfixe "ABC":
-- CREATE TABLE ABC_PROCESS_CONTEXT (...)
-- CREATE TABLE ABC_HISTORIQUE_EXECUTION_NOEUD (...)
-- CREATE INDEX IX_ABC_01_PROCESS_CONTEXT ON ABC_PROCESS_CONTEXT(ID_ENTI_AFFA);
-- CREATE INDEX IX_ABC_02_PROCESS_CONTEXT ON ABC_PROCESS_CONTEXT(STAT_PROCS);
-- CREATE INDEX IX_ABC_03_PROCESS_CONTEXT ON ABC_PROCESS_CONTEXT(DH_DEB);
-- CREATE INDEX IX_ABC_01_HISTORIQUE_EXECUTION_NOEUD ON ABC_HISTORIQUE_EXECUTION_NOEUD(NO_SEQ_PROCS);
-- CREATE INDEX IX_ABC_02_HISTORIQUE_EXECUTION_NOEUD ON ABC_HISTORIQUE_EXECUTION_NOEUD(ID_NOEUD);
-- CREATE INDEX IX_ABC_03_HISTORIQUE_EXECUTION_NOEUD ON ABC_HISTORIQUE_EXECUTION_NOEUD(DH_DEB);
